language: csharp
sudo: false
solution: ShogiCore.sln

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gtk-sharp2

script:
  - make build || true
  - mono packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ShogiCoreTest/bin/Debug/ShogiCoreTest.dll
